#ifndef ENDING_CREDITS_JAM_H
#define ENDING_CREDITS_JAM_H

#include "game/ending/ending_credits_character.h"

void updateEndingJamFinalPose(EndingCreditsCharacterActor *arg0);
void updateEndingJamStartFinalPose(EndingCreditsCharacterActor *arg0);
void waitEndingJamPhase40(EndingCreditsCharacterActor *arg0);
void updateEndingJamWaitBeforePhase40(EndingCreditsCharacterActor *arg0);
void updateEndingJamPhase3FAnim3(EndingCreditsCharacterActor *arg0);
void updateEndingJamPhase3FAnim2(EndingCreditsCharacterActor *arg0);
void updateEndingJamPhase3FAnim1(EndingCreditsCharacterActor *arg0);
void waitEndingJamPhase3E(EndingCreditsCharacterActor *arg0);
void updateEndingJamSetPhase3D(EndingCreditsCharacterActor *arg0);
void updateEndingJamPhase3DPrep(EndingCreditsCharacterActor *arg0);
void updateEndingJamWaitBeforePhase3D(EndingCreditsCharacterActor *arg0);
void updateEndingJamWaitBeforeIdleAnim2(EndingCreditsCharacterActor *arg0);
void updateEndingJamWaitBeforeIdleAnim1(EndingCreditsCharacterActor *arg0);
void updateEndingJamHopRightToIdle(EndingCreditsCharacterActor *arg0);
void updateEndingJamSlideLeftSetPhase3B(EndingCreditsCharacterActor *arg0);
void waitEndingJamPhase3A(EndingCreditsCharacterActor *arg0);
void updateEndingJamSlideRightToCenter(EndingCreditsCharacterActor *arg0);
void waitEndingJamPhase38(EndingCreditsCharacterActor *arg0);
void updateEndingJamSlideLeftFromFarRight(EndingCreditsCharacterActor *arg0);
void waitEndingJamPhase33Aura(EndingCreditsCharacterActor *arg0);
void updateEndingJamDashOffLeftSetPhase31(EndingCreditsCharacterActor *arg0);
void updateEndingJamVanishRetreat(EndingCreditsCharacterActor *arg0);
void waitEndingJamPhase2F(EndingCreditsCharacterActor *arg0);
void updateEndingJamDriftAfterPhase2D(EndingCreditsCharacterActor *arg0);
void updateEndingJamWaitThenSetPhase2C(EndingCreditsCharacterActor *arg0);
void updateEndingJamRunLeftThenPhase2C(EndingCreditsCharacterActor *arg0);
void updateEndingJamSlideFarLeft(EndingCreditsCharacterActor *arg0);
void waitEndingJamPhase2A(EndingCreditsCharacterActor *arg0);
void updateEndingJamSlideRightToPose(EndingCreditsCharacterActor *arg0);
void waitEndingJamPhase28(EndingCreditsCharacterActor *arg0);
void updateEndingJamSlideRightToMarker(EndingCreditsCharacterActor *arg0);
void waitEndingJamBeforeMarkerSlide(EndingCreditsCharacterActor *arg0);
void updateEndingJamSlideLeftToMarker(EndingCreditsCharacterActor *arg0);
void updateEndingJamWaitThenSetPhase27(EndingCreditsCharacterActor *arg0);
void updateEndingJamSlideRightToPhase27Start(EndingCreditsCharacterActor *arg0);
void startEndingJamPhase26Slide(EndingCreditsCharacterActor *arg0);
void updateEndingJamSlideLeftSetPhase25(EndingCreditsCharacterActor *arg0);
void waitEndingJamBeforeDiagonalSlide(EndingCreditsCharacterActor *arg0);
void updateEndingJamDiagonalSlideSetPhase22(EndingCreditsCharacterActor *arg0);
void waitEndingJamPhase21Aura(EndingCreditsCharacterActor *arg0);
void updateEndingJamExitLeftAfterPhase21(EndingCreditsCharacterActor *arg0);
void updateEndingJamAfterVanishWait(EndingCreditsCharacterActor *arg0);
void updateEndingJamWaitBeforeVanishReturn(EndingCreditsCharacterActor *arg0);
void startEndingJamVanishReturn(EndingCreditsCharacterActor *arg0);
void updateEndingJamSlideLeftThenVanish(EndingCreditsCharacterActor *arg0);
void waitEndingJamPhase1E(EndingCreditsCharacterActor *arg0);
void updateEndingJamExitLeftSetPhase1D(EndingCreditsCharacterActor *arg0);
void updateEndingJamRepeatAnimThenVanish(EndingCreditsCharacterActor *arg0);
void waitEndingJamPhase1C(EndingCreditsCharacterActor *arg0);
void updateEndingJamWaitBeforePhase1C(EndingCreditsCharacterActor *arg0);
void updateEndingJamStepBackAfterHandshake(EndingCreditsCharacterActor *arg0);
void waitEndingJamHandshakeExit(EndingCreditsCharacterActor *arg0);
void updateEndingJamHandshakeLoopThird(EndingCreditsCharacterActor *arg0);
void updateEndingJamHandshakeLoopSecond(EndingCreditsCharacterActor *arg0);
void updateEndingJamHandshakeLoopFirst(EndingCreditsCharacterActor *arg0);
void startEndingJamHandshakeLoop(EndingCreditsCharacterActor *arg0);
void updateEndingJamSlideRightUntilPhase18(EndingCreditsCharacterActor *arg0);
void waitEndingJamPhase17(EndingCreditsCharacterActor *arg0);
void updateEndingJamSlideLeftToIdle(EndingCreditsCharacterActor *arg0);
void startEndingJamIdleAfterAnim(EndingCreditsCharacterActor *arg0);
void updateEndingJamWaitBeforeIdleAnimB(EndingCreditsCharacterActor *arg0);
void updateEndingJamWaitBeforeIdleAnimA(EndingCreditsCharacterActor *arg0);
void updateEndingJamHopRightToPose(EndingCreditsCharacterActor *arg0);
void waitEndingJamPhase15(EndingCreditsCharacterActor *arg0);
void updateEndingJamSlideLeftToPhase15Wait(EndingCreditsCharacterActor *arg0);
void waitEndingJamPhase13(EndingCreditsCharacterActor *arg0);
void initEndingCreditsJam(EndingCreditsCharacterActor *arg0);

#endif
