#ifndef RACE_UI_EFFECTS_H
#define RACE_UI_EFFECTS_H

#include "common.h"
#include "game/race/ui/race_hud.h"

struct CallbackTask;
struct RaceUiAlpha18Actor;
struct RaceUiAlpha1AActor;
struct RaceUiAlphaActor;
struct RaceUiAnimatedTextActor;
struct RaceUiCounterActor;
struct RaceUiCourseSpriteActor;
struct RaceUiCourseStatsActor;
struct RaceUiDualCounterActor;
struct RaceUiEffectParticleActor;
struct RaceUiFadingImpactActor;
struct RaceUiFadingTrailActor;
struct RaceUiGfxCommandActor;
struct RaceUiOverlayActor;
struct RaceUiOrbitingSpriteActor;
struct RaceUiPodiumTrailActor;
struct RaceUiPopupActor;
struct RaceUiProjectileActor;
struct RaceUiPrizePayoutActor;
struct RaceUiPromptActor;
struct RaceUiRankParticleActor;
struct RaceUiRankTextRenderActor;
struct RaceUiRankTrailActor;
struct RaceUiResultsBannerActor;
struct RaceUiRisingTrailActor;
struct RaceUiScaledParticleActor;
struct RaceUiSingleTrailActor;
struct RaceUiSlideActor;
struct RaceUiSnowboardTrailActor;
struct RaceUiSnowboardTrailPlayer;
struct RaceUiSparkleActor;
struct RaceUiSpinningParticleActor;
struct RaceUiTextParticleActor;
struct RaceUiThrownTrailActor;
struct RaceUiTimeTrialRecordDeltaPopupActor;
struct RaceUiTrailingParticleActor;
struct RaceUiTransitionActor;
struct RaceUiTransitionRenderActor;
struct RaceUiTripleParticleActor;

void renderRaceCourseSlideSprite(struct RaceUiSlideActor *arg0);
void updateRaceCourseSlideSprite(struct RaceUiSlideActor *arg0);
void initRaceCourseSlideSprite(struct RaceUiSlideActor *arg0);
void drawRaceUiBoardReversePrompt(struct RaceUiPromptActor *arg0);
void updateRaceUiBoardReversePrompt(struct RaceUiPromptActor *arg0);
void initRaceUiBoardReversePrompt(struct RaceUiPromptActor *arg0);
void drawRaceUiTrickScorePopup(struct RaceUiPopupActor *arg0);
void updateRaceUiTrickScorePopupSlideOut(struct RaceUiPopupActor *arg0);
void updateRaceUiTrickScorePopupHold(struct RaceUiPopupActor *arg0);
void updateRaceUiTrickScorePopupSlideIn(struct RaceUiPopupActor *arg0);
void initRaceUiTrickScorePopup(struct RaceUiPopupActor *arg0);
void spawnRaceUiTrickScorePopup(void *arg0, s16 arg1);
void drawRaceUiCrashScorePopup(struct RaceUiPopupActor *arg0);
void updateRaceUiCrashScorePopupSlideOut(struct RaceUiPopupActor *arg0);
void updateRaceUiCrashScorePopupHold(struct RaceUiPopupActor *arg0);
void updateRaceUiCrashScorePopupSlideIn(struct RaceUiPopupActor *arg0);
void initRaceUiCrashScorePopup(struct RaceUiPopupActor *arg0);
void func_80057E10(void *arg0);
void func_80057E60(void *arg0);
void func_80057E90(struct RaceUiAlpha18Actor *arg0);
void func_8005804C(struct RaceUiAlpha18Actor *arg0);
void func_8005812C(void *arg0);
void func_8005827C(void *arg0);
void func_80058360(struct RaceUiAlpha18Actor *arg0);
void func_800584A0(void *arg0);
void func_80058538(void *arg0);
void func_80058610(struct RaceUiAlpha18Actor *arg0);
void updateRaceUiPrizePayoutWaitBeforeMoneyCount(struct RaceUiPrizePayoutActor *arg0);
void updateRaceUiPrizePayoutRevealGetCoin(struct RaceUiPrizePayoutActor *arg0);
void updateRaceUiPrizePayoutRevealRankPrize(struct RaceUiPrizePayoutActor *arg0);
void updateRaceUiPrizePayoutShowRankPrize(struct RaceUiPrizePayoutActor *arg0);
void updateRaceUiPrizePayoutFadeIn(struct RaceUiPrizePayoutActor *arg0);
void initRaceUiPrizePayout(struct RaceUiPrizePayoutActor *arg0);
void func_80058C00(struct RaceUiResultsBannerActor *arg0);
void func_8005905C(void *arg0);
void func_80059518(struct RaceUiResultsBannerActor *arg0);
void updateRaceUiResultsBannerConfirmed(struct RaceUiResultsBannerActor *arg0);
void updateRaceUiResultsBannerWaitForInput(struct RaceUiResultsBannerActor *arg0);
void updateRaceUiResultsBannerFadeIn(struct RaceUiResultsBannerActor *arg0);
void initRaceUiResultsBanner(struct RaceUiResultsBannerActor *arg0);
void func_80059A04(RaceTimer *arg0, s32 x, s32 y, s32 color);
void func_80059C34(struct RaceUiCourseStatsActor *arg0);
void func_80059E5C(struct RaceUiAlpha1AActor *arg0);
void func_80059F6C(struct RaceUiAlpha18Actor *arg0);
void func_8005A07C(struct RaceUiCourseStatsActor *arg0);
void func_8005A0E0(struct RaceUiCourseStatsActor *arg0);
void func_8005A184(struct RaceUiCourseStatsActor *arg0);
void func_8005A1FC(struct RaceUiCourseStatsActor *arg0);
void func_8005A288(struct RaceUiCourseStatsActor *arg0);
void func_8005A2F0(struct RaceUiCourseStatsActor *arg0);
void func_8005A31C(struct RaceUiAlpha18Actor *arg0);
void func_8005A4BC(struct RaceUiCounterActor *arg0);
void func_8005A884(struct RaceUiPopupActor *arg0);
void func_8005AAE4(struct RaceUiAlpha18Actor *arg0);
void func_8005AC44(struct RaceUiCounterActor *arg0);
void func_8005AE1C(void *arg0);
void func_8005AEB0(void *arg0);
void func_8005AF2C(void *arg0);
void func_8005AFEC(void *arg0);
void func_8005B068(struct RaceUiCounterActor *arg0);
void func_8005B14C(struct RaceUiCounterActor *arg0);
void updateRaceUiHitPrizeWaitBeforePayout(struct RaceUiCounterActor *arg0);
void updateRaceUiHitPrizeRevealTotalMoney(struct RaceUiCounterActor *arg0);
void func_8005B49C(struct RaceUiCounterActor *arg0);
void updateRaceUiHitPrizeRevealPerfectHit(struct RaceUiCounterActor *arg0);
void updateRaceUiHitPrizeHoldHitPrize(struct RaceUiCounterActor *arg0);
void updateRaceUiHitPrizeWaitBeforeHitPrize(struct RaceUiCounterActor *arg0);
void updateRaceUiHitPrizeFadeIn(struct RaceUiCounterActor *arg0);
void initRaceUiHitPrizePayout(struct RaceUiCounterActor *arg0);
void func_8005B8E8(struct RaceUiAlphaActor *arg0);
void func_8005B9F8(struct RaceUiDualCounterActor *arg0);
void func_8005BE68(struct RaceUiPopupActor *arg0);
void func_8005C03C(struct RaceUiAlphaActor *arg0);
void func_8005C14C(struct RaceUiDualCounterActor *arg0);
void func_8005C3E4(void *arg0);
void func_8005C448(void *arg0);
void func_8005C4EC(void *arg0);
void func_8005C568(struct RaceUiDualCounterActor *arg0);
void func_8005C64C(struct RaceUiDualCounterActor *arg0);
void func_8005C89C(struct RaceUiDualCounterActor *arg0);
void updateRaceUiCourseRecordHoldFinalMoney(struct RaceUiDualCounterActor *arg0);
void updateRaceUiCourseRecordRevealFinalMoney(struct RaceUiDualCounterActor *arg0);
void updateRaceUiCourseRecordRevealPerfectGet(struct RaceUiDualCounterActor *arg0);
void func_8005CB74(struct RaceUiDualCounterActor *arg0);
void func_8005CC54(struct RaceUiDualCounterActor *arg0);
void func_8005CD10(struct RaceUiDualCounterActor *arg0);
void func_8005CDB0(struct RaceUiDualCounterActor *arg0);
void func_8005CE4C(struct RaceUiDualCounterActor *arg0);
void func_8005CF60(struct RaceUiDualCounterActor *arg0);
void func_8005D1CC(struct RaceUiCourseStatsActor *arg0);
void func_8005D558(struct RaceUiCourseStatsActor *arg0);
void func_8005D860(struct RaceUiAlpha18Actor *arg0);
void func_8005D9B4(struct RaceUiAlpha18Actor *arg0);
void func_8005DB3C(void *arg0);
void func_8005DBD0(void *arg0);
void func_8005DC4C(void *arg0);
void func_8005DD0C(void *arg0);
void updateRaceUiTrickPrizePayoutWaitForConfirm(struct RaceUiCourseStatsActor *arg0);
void func_8005DE6C(struct RaceUiCourseStatsActor *arg0);
void updateRaceUiTrickPrizePayoutHoldMoneyRow(struct RaceUiCourseStatsActor *arg0);
void updateRaceUiTrickPrizePayoutRevealMoneyRow(struct RaceUiCourseStatsActor *arg0);
void updateRaceUiTrickPrizePayoutRevealCompleteBonus(struct RaceUiCourseStatsActor *arg0);
void updateRaceUiTrickPrizePayoutRevealMakeBonus(struct RaceUiCourseStatsActor *arg0);
void updateRaceUiTrickPrizePayoutRevealTrickPrize(struct RaceUiCourseStatsActor *arg0);
void updateRaceUiTrickPrizePayoutWaitBeforeReveal(struct RaceUiCourseStatsActor *arg0);
void updateRaceUiTrickPrizePayoutFadeIn(struct RaceUiCourseStatsActor *arg0);
void initRaceUiTrickPrizePayout(struct RaceUiCourseStatsActor *arg0);
void drawRaceUiResultAwardBadge(struct CallbackTask *task);
void updateRaceUiResultAwardBadgeDelay(struct CallbackTask *task);
void func_8005E6D0(struct RaceUiSparkleActor *arg0);
void func_8005EA4C(struct RaceUiSparkleActor *arg0);
void func_8005ECA8(struct RaceUiSparkleActor *arg0);
void func_8005EFFC(struct RaceUiSparkleActor *arg0);
void func_8005F174(struct RaceUiSparkleActor *arg0);
void spawnRacePlayerSparkleEffect(s16 arg0);
#define renderRaceUiSnowboardTrailEffect func_8005F2DC
#define updateRaceUiSnowboardTrailEffect func_8005F448
#define initRaceUiSnowboardTrailEffect func_8005F56C
#define spawnRaceUiSnowboardTrailEffect func_8005F5C8
void renderRaceUiSnowboardTrailEffect(struct RaceUiSnowboardTrailActor *arg0);
void updateRaceUiSnowboardTrailEffect(struct RaceUiSnowboardTrailActor *arg0);
void initRaceUiSnowboardTrailEffect(struct RaceUiSnowboardTrailActor *arg0);
void spawnRaceUiSnowboardTrailEffect(struct RaceUiSnowboardTrailPlayer *player);
void func_8005F6A4(struct RaceUiRankTrailActor *arg0);
void func_8005F828(struct RaceUiRankTrailActor *arg0);
void initRaceUiItemStealTrailEffect(struct RaceUiRankTrailActor *arg0);
void func_8005FBA8(struct RaceUiAnimatedTextActor *arg0);
void func_8005FED0(struct RaceUiTextParticleActor *arg0);
void updateRaceUiBurstTextParticle(struct RaceUiTextParticleActor *arg0);
void initRaceUiBurstTextParticle(struct RaceUiTextParticleActor *arg0);
void spawnRaceUiBurstTextParticle(void *arg0, void *arg1, void *arg2, s16 arg3);
void spawnRaceUiAltBurstTextParticle(void *arg0, void *arg1, void *arg2, s16 arg3);
void func_80060544(struct RaceUiPodiumTrailActor *arg0);
void updateGhostSlowdownDriftAway(struct RaceUiPodiumTrailActor *arg0);
void updateGhostSlowdownImpact(struct RaceUiPodiumTrailActor *arg0);
void updateGhostSlowdownRise(struct RaceUiPodiumTrailActor *arg0);
void initGhostSlowdownActor(struct RaceUiPodiumTrailActor *arg0);
void spawnGhostSlowdownTargets(s16 arg0);
void drawRaceUiScorePopup(struct RaceUiPopupActor *arg0);
void updateRaceUiScorePopupSlideOut(struct RaceUiPopupActor *arg0);
void updateRaceUiScorePopupHold(struct RaceUiPopupActor *arg0);
void updateRaceUiScorePopupSlideIn(struct RaceUiPopupActor *arg0);
void initRaceUiScorePopup(struct RaceUiPopupActor *arg0);
void spawnRaceUiScorePopup(void *arg0, s16 arg1);
void renderRaceCourseTripleParticle(struct RaceUiTripleParticleActor *arg0);
void updateRaceCourseTripleParticle(struct RaceUiTripleParticleActor *arg0);
void initRaceCourseTripleParticle(struct RaceUiTripleParticleActor *arg0);
void func_80061484(struct RaceUiRankTrailActor *arg0);
void func_800615BC(struct RaceUiRankTrailActor *arg0);
void initRaceUiHeavyKnockdownTrailEffect(void *arg0);
void func_800617EC(struct RaceUiRisingTrailActor *arg0);
void func_80061984(struct RaceUiThrownTrailActor *arg0);
void func_80061A98(struct RaceUiThrownTrailActor *arg0);
void func_80061AF4(s16 arg0, void *arg1, void *arg2, s16 arg3);
void renderRaceUiSingleTrailEffect(struct RaceUiSingleTrailActor *arg0);
void updateRaceUiSingleTrailEffect(struct RaceUiSingleTrailActor *arg0);
void initRaceUiSingleTrailEffect(struct RaceUiSingleTrailActor *arg0);
void func_80061DE8(struct RaceUiFadingTrailActor *arg0);
void func_80061F38(struct RaceUiFadingImpactActor *arg0);
void initRaceUiFadingImpact(struct RaceUiFadingImpactActor *arg0);
void spawnRaceUiFadingImpact(void *arg0, void *arg1, void *arg2);
void func_800622B0(struct RaceUiTransitionRenderActor *arg0);
void func_800623E8(struct RaceUiTransitionActor *arg0);
void initRaceUiSpinHitTransitionEffect(struct RaceUiTransitionActor *arg0);
void func_800625D8(struct RaceUiOrbitingSpriteActor *arg0);
void func_800628DC(struct RaceUiOrbitingSpriteActor *arg0);
void func_80062A10(struct RaceUiOrbitingSpriteActor *arg0);
void spawnRaceUiStunOrbitingIcons(s16 arg0);
void renderIceCourseBumper(struct RaceUiScaledParticleActor *arg0);
void updateIceCourseBumper(struct RaceUiScaledParticleActor *arg0);
void initIceCourseBumper(struct RaceUiScaledParticleActor *arg0);
void func_80062F6C(struct RaceUiTrailingParticleActor *arg0);
void func_80063164(struct RaceUiTrailingParticleActor *arg0);
void func_800631B0(struct RaceUiTrailingParticleActor *arg0);
void renderRaceCourseSpinningObject(struct RaceUiSpinningParticleActor *arg0);
void updateRaceCourseSpinningObject(struct RaceUiSpinningParticleActor *arg0);
void initRaceCourseSpinningObject(struct RaceUiSpinningParticleActor *arg0);
void renderCourseStartFinishSprite(struct RaceUiCourseSpriteActor *arg0);
void updateCourseStartFinishSprite(struct RaceUiCourseSpriteActor *actor);
void initCourseStartFinishSprite(struct RaceUiCourseSpriteActor *actor);
void func_80063A9C(struct RaceUiEffectParticleActor *arg0);
void func_80063E70(struct RaceUiEffectParticleActor *arg0);
void func_80063FC0(struct RaceUiEffectParticleActor *actor);
void renderRaceCourseRankModel(struct RaceUiRankParticleActor *arg0);
void updateRaceCourseRankModel(struct RaceUiRankParticleActor *arg0);
void initRaceCourseRankModel(struct RaceUiRankParticleActor *actor);
void func_800643B4(struct RaceUiProjectileActor *arg0, u16 *arg1);
s32 func_80064414(struct RaceUiProjectileActor *arg0);
void func_80064470(struct RaceUiProjectileActor *arg0);
void func_800647E0(struct RaceUiProjectileActor *arg0);
void func_80064914(struct RaceUiProjectileActor *arg0);
void func_80064B28(struct RaceUiProjectileActor *arg0);
void func_80064C68(struct RaceUiProjectileActor *arg0);
void func_80064D88(struct RaceUiProjectileActor *arg0);
void initForwardActionProjectileEffect(struct RaceUiProjectileActor *arg0);
void drawTimeTrialRecordDeltaPopup(struct RaceUiTimeTrialRecordDeltaPopupActor *arg0);
void updateTimeTrialRecordDeltaPopupSlideOut(struct RaceUiTimeTrialRecordDeltaPopupActor *arg0);
void updateTimeTrialRecordDeltaPopupHold(struct RaceUiTimeTrialRecordDeltaPopupActor *arg0);
void updateTimeTrialRecordDeltaPopupSlideIn(struct RaceUiTimeTrialRecordDeltaPopupActor *arg0);
void initTimeTrialRecordDeltaPopup(struct RaceUiTimeTrialRecordDeltaPopupActor *arg0);
void func_800651BC(struct RaceUiGfxCommandActor *arg0);
void updateRaceCourseCoinMarkers(struct RaceUiGfxCommandActor *arg0);
void initRaceCourseCoinMarkerMatrices(struct RaceUiGfxCommandActor *arg0);
void initRaceCourseCoinMarkers(struct RaceUiGfxCommandActor *arg0);
void func_80065808(struct RaceUiOverlayActor *arg0);
void updateRaceStartOverlayFallOut(struct RaceUiOverlayActor *arg0);
void func_80065D24(struct RaceUiOverlayActor *arg0);
void func_80065E0C(struct RaceUiOverlayActor *arg0);
void func_80065E90(struct RaceUiOverlayActor *arg0);
void renderRaceScoreAttackRings(struct RaceUiRankTextRenderActor *arg0);
void updateRaceScoreAttackRings(void *arg0);
void initRaceScoreAttackRingMatrices(struct RaceUiRankTextRenderActor *arg0);
void initRaceScoreAttackRings(struct RaceUiRankTextRenderActor *arg0);

#endif
