#include "game/engine/system_render.h"

#define RELOCATABLE_HEAP_SIZE 0x1C0000
#define INITIAL_BOOT_STACK_SIZE 0x2000
#define BOOT_THREAD_STACK_SIZE 0x2000
#define GAME_THREAD_STACK_SIZE 0x4000
#define REGION_ALLOCATION_BUFFER_SIZE 0x37B80

u8 gRelocatableHeapStart[RELOCATABLE_HEAP_SIZE];
static u8 sInitialBootStack[INITIAL_BOOT_STACK_SIZE];
u8 gBootThreadStack[BOOT_THREAD_STACK_SIZE];
u8 gGameThreadStack[GAME_THREAD_STACK_SIZE];
u8 D_80328480[REGION_ALLOCATION_BUFFER_SIZE];
u8 D_80360000[RSP_OUTPUT_BUFFER_SIZE];
u8 D_80368000[RSP_YIELD_BUFFER_SIZE];
u8 D_80368C00[RSP_DRAM_STACK_SIZE];
u16 gDepthBuffer[FRAMEBUFFER_PIXEL_COUNT];
u16 gFramebuffers[FRAMEBUFFER_COUNT][FRAMEBUFFER_PIXEL_COUNT];
