name: Ninja Land
key: ninja_land
enum: NINJA_LAND
legacy_id: 8
kind: secret
uses: [race]
assets:
  graphics: { symbol: NINJA_LAND_COURSE_GRAPHICS, rom_start: '0x1384B0', rom_end: '0x13F3B0' }
  model_resources: { symbol: NINJA_LAND_COURSE_MODEL_RESOURCES, rom_start: '0x1C9630', rom_end: '0x1D3070' }
  surface_data: { symbol: NINJA_LAND_COURSE_SURFACE_DATA, rom_start: '0x23FCC0', rom_end: '0x241160' }
  sprites: { symbol: NINJA_LAND_COURSE_SPRITES, rom_start: '0x1EEEA0', rom_end: '0x1EF1D0' }
render:
  main_display_list: NINJA_LAND_COURSE_DISPLAY_LIST
  backdrop_display_lists: [NINJA_LAND_COURSE_BACKDROP_DISPLAY_LIST]
  scenery_entries: gNinjaLandCourseSceneryEntries
  scrolling_textures: []
