#ifndef MULTIPLAYER_COURSE_SELECT_MENU_H
#define MULTIPLAYER_COURSE_SELECT_MENU_H

#include "common.h"

#define MULTIPLAYER_COURSE_SELECT_DEFAULT_COURSE_COUNT 12
#define MULTIPLAYER_COURSE_SELECT_COLUMN_COUNT 10

extern s8 gMultiplayerCourseSelectDefaultCourseIds[MULTIPLAYER_COURSE_SELECT_DEFAULT_COURSE_COUNT];
extern s16 gCourseSelectColumnSoundEffects[MULTIPLAYER_COURSE_SELECT_COLUMN_COUNT];

void initMultiplayerCourseSelectMenu(void);
void updateMultiplayerCourseSelectMenu(void);
void fadeOutMultiplayerCourseSelectMenu(void);

#endif
