#ifndef RACE_PLAYER_UPDATE_H
#define RACE_PLAYER_UPDATE_H

#include "common.h"
struct RacePlayer;

typedef struct {
    s16 unk0;
    s16 unk2;
    s16 unk4;
    s16 unk6;
    s16 unk8;
    s16 unkA;
    s16 unkC;
    s16 unkE;
    s16 unk10;
} PlayerTuningRow;

extern PlayerTuningRow gRacePlayerBoardTuningRows[];
extern PlayerTuningRow gRacePlayerCharacterTuningRows[];
extern PlayerTuningRow gRacePlayerDemoBoardTuningRows[];
extern PlayerTuningRow gRacePlayerDemoCharacterTuningRows[];

void initRacePlayers(void);
void applyRacePlayerTuning(struct RacePlayer *player);
void initRacePlayer(struct RacePlayer *player);
void updateRacePlayers(void);
void updateRacePlayer(struct RacePlayer *player);
void updateRacePlayerMotionFeedback(struct RacePlayer *player);
void updateRacePlayerMode00Grounded(struct RacePlayer *player);
void updateRacePlayerMode29Crash(struct RacePlayer *player);
void updateRacePlayerMode01JumpStart(struct RacePlayer *player);
void updateRacePlayerMode22Airborne(struct RacePlayer *player);
void dispatchRacePlayerAirborneMode(struct RacePlayer *player);
void updateRacePlayerAirborneLaunch(struct RacePlayer *player);
void updateRacePlayerAirborneCruise(struct RacePlayer *player);
void resetRacePlayerTrickSubstate(struct RacePlayer *player);
void updateRacePlayerTrickSubstate(struct RacePlayer *player);
void updateRacePlayerTrickSubstateStart(struct RacePlayer *player);
void updateRacePlayerTrickSubstateHold(struct RacePlayer *player);
void updateRacePlayerTrickSubstateFinish(struct RacePlayer *player);
void updateRacePlayerTrickSubstateNoop(s32 arg0);
void updateRacePlayerMode13AerialTrick(struct RacePlayer *player);
void updateRacePlayerMode15AerialTrick(struct RacePlayer *player);
void updateRacePlayerMode16AerialTrick(struct RacePlayer *player);
void updateRacePlayerMode17AerialTrick(struct RacePlayer *player);
void updateRacePlayerMode18AerialTrick(struct RacePlayer *player);
void updateRacePlayerMode19AerialTrick(struct RacePlayer *player);
void updateRacePlayerMode20AerialTrick(struct RacePlayer *player);
void updateRacePlayerMode21AerialTrick(struct RacePlayer *player);
void updateRacePlayerMode31AerialTrick(struct RacePlayer *player);
void updateRacePlayerMode41AerialTrick(struct RacePlayer *player);
void updateRacePlayerMode42AerialTrick(struct RacePlayer *player);
void updateRacePlayerMode43AerialTrick(struct RacePlayer *player);
void updateRacePlayerMode32AerialTrick(struct RacePlayer *player);
void updateRacePlayerMode33AerialTrick(struct RacePlayer *player);
void updateRacePlayerMode34AerialTrick(struct RacePlayer *player);
void updateRacePlayerMode44AerialTrick(struct RacePlayer *player);
void updateRacePlayerMode45AerialTrick(struct RacePlayer *player);
void updateRacePlayerMode46AerialTrick(struct RacePlayer *player);
void updateRacePlayerMode35AerialTrick(struct RacePlayer *player);
void updateRacePlayerMode36AerialTrick(struct RacePlayer *player);
void updateRacePlayerMode47AerialTrick(struct RacePlayer *player);
void updateRacePlayerMode48AerialTrick(struct RacePlayer *player);
void updateRacePlayerMode49AerialTrick(struct RacePlayer *player);
void updateRacePlayerMode37AerialTrick(struct RacePlayer *player);
void updateRacePlayerMode50AerialTrick(struct RacePlayer *player);
void updateRacePlayerMode51AerialTrick(struct RacePlayer *player);
void updateRacePlayerMode52AerialTrick(struct RacePlayer *player);
void updateRacePlayerMode38AerialTrick(struct RacePlayer *player);
void updateRacePlayerMode53AerialTrick(struct RacePlayer *player);
void updateRacePlayerMode54AerialTrick(struct RacePlayer *player);
void updateRacePlayerMode39AerialTrick(struct RacePlayer *player);
void updateRacePlayerMode55AerialTrick(struct RacePlayer *player);
void updateRacePlayerMode56AerialTrick(struct RacePlayer *player);
void updateRacePlayerMode57AerialTrick(struct RacePlayer *player);
void updateRacePlayerMode03Nudge(struct RacePlayer *player);
void updateRacePlayerMode04Spinout(struct RacePlayer *player);
void updateRacePlayerMode05SpinoutStun(struct RacePlayer *player);
void updateRacePlayerMode08SpinoutRecover(struct RacePlayer *player);
void updateRacePlayerMode06TerrainFall(struct RacePlayer *player);
void updateRacePlayerMode28TerrainFallWithItemEffect(struct RacePlayer *player);
void updateRacePlayerMode09TerrainCrash(struct RacePlayer *player);
void updateRacePlayerMode10TerrainCrashSlide(struct RacePlayer *player);
void updateRacePlayerMode12LaunchRecover(struct RacePlayer *player);
void updateRacePlayerMode11LaunchHit(struct RacePlayer *player);
void updateRacePlayerMode26Tumble(struct RacePlayer *player);
void updateRacePlayerMode14PushHit(struct RacePlayer *player);
void updateRacePlayerMode23ItemSteal(struct RacePlayer *player);
void updateRacePlayerMode24HeavyKnockdown(struct RacePlayer *player);
void updateRacePlayerMode25SpinHit(struct RacePlayer *player);
void updateRacePlayerMode27Slide(struct RacePlayer *player);
void updateRacePlayerMode40Stun(struct RacePlayer *player);
void dispatchRacePlayerMode07CourseObject(struct RacePlayer *player);
void updateRacePlayerMode07AlignToLaunchRamp(struct RacePlayer *player);
void updateRacePlayerMode07StartLaunchRamp(struct RacePlayer *player);
void updateRacePlayerMode07LaunchRampTakeoff(struct RacePlayer *player);
void updateRacePlayerMode07LaunchRampSpin(struct RacePlayer *player);
void updateRacePlayerMode07LaunchRampPose(struct RacePlayer *player);
void updateRacePlayerMode07LaunchRampDrift(struct RacePlayer *player);
void updateRacePlayerMode07LaunchRampClimb(struct RacePlayer *player);
void updateRacePlayerMode07SpiralExit(struct RacePlayer *player);
s32 tryStartRacePlayerCourseObjectMode(s16 arg0);
void dispatchRacePlayerMode30Attack(struct RacePlayer *player);
void updateRacePlayerMode30AttackApproach(struct RacePlayer *player);
void updateRacePlayerMode30AttackResolve(struct RacePlayer *player);
void dispatchRacePlayerMode32Character(struct RacePlayer *player);
void updateRacePlayerMode32Character0(struct RacePlayer *player);
void updateRacePlayerMode32Character1(struct RacePlayer *player);
void updateRacePlayerMode32Character2(struct RacePlayer *player);
void updateRacePlayerMode32Character3(struct RacePlayer *player);
void updateRacePlayerMode32Character4(struct RacePlayer *player);
void updateRacePlayerMode32Character5(struct RacePlayer *player);
void dispatchRacePlayerMode35Character(struct RacePlayer *player);
void updateRacePlayerMode35Character0(struct RacePlayer *player);
void updateRacePlayerMode35Character1(struct RacePlayer *player);
void updateRacePlayerMode35Character2(struct RacePlayer *player);
void updateRacePlayerMode35Character3(struct RacePlayer *player);
void updateRacePlayerMode35Character4(struct RacePlayer *player);
void updateRacePlayerMode35Character5(struct RacePlayer *player);
void updateRacePlayersPostUpdate(void);
void updateRacePlayerPostUpdate(struct RacePlayer *player);
void updateRacePlayerPostUpdateNoop(struct RacePlayer *player);
void updateRacePlayerPostUpdateCourseObject(struct RacePlayer *player);
void updateRacePlayerPostUpdateMode00(struct RacePlayer *player);
void updateRacePlayerVoiceSounds(struct RacePlayer *player);
void updateRacePlayerLoopingSound(struct RacePlayer *player);
void updateRacePlayerPostUpdateMode22(struct RacePlayer *player);
void updateRacePlayerPostUpdateAirborneTrick(struct RacePlayer *player);
void updateRacePlayerPostUpdateAirborneLaunch(struct RacePlayer *player);
void updateRacePlayerPostUpdateNudge(struct RacePlayer *player);
void updateRacePlayerPostUpdateMode29(struct RacePlayer *player);
void updateRacePlayerPostUpdateAttack(struct RacePlayer *player);

#endif
