#ifndef ASSETS_H
#define ASSETS_H

#include "game/engine/system_runtime.h"

#define ASSET_START(id) ((void *)&id##_ROM_START)
#define ASSET_END(id) ((void *)&id##_ROM_END)
#define ASSET_SIZE(id) ((u8 *)&id##_ROM_END - (u8 *)&id##_ROM_START)

USE_ASSET(LEVEL_BIG_SNOWMAN);
USE_ASSET(LEVEL_SUNSET_ROCK);
USE_ASSET(LEVEL_NIGHT_HIGHWAY);
USE_ASSET(LEVEL_GRASS_VALLEY);
USE_ASSET(LEVEL_DIZZY_LAND);
USE_ASSET(LEVEL_QUICKSAND_VALLEY);
USE_ASSET(LEVEL_SILVER_MOUNTAIN);
USE_ASSET(LEVEL_ANIMAL_LAND);
USE_ASSET(LEVEL_NINJA_LAND);
USE_ASSET(LEVEL_ROOKIE_MOUNTAIN);

USE_ASSET(LEVEL_BIG_SNOWMAN_TEXTURES);
USE_ASSET(LEVEL_SUNSET_ROCK_TEXTURES);
USE_ASSET(LEVEL_NIGHT_HIGHWAY_TEXTURES);
USE_ASSET(LEVEL_GRASS_VALLEY_TEXTURES);
USE_ASSET(LEVEL_DIZZY_LAND_TEXTURES);
USE_ASSET(LEVEL_QUICKSAND_VALLEY_TEXTURES);
USE_ASSET(LEVEL_SILVER_MOUNTAIN_TEXTURES);
USE_ASSET(LEVEL_ANIMAL_LAND_TEXTURES);
USE_ASSET(LEVEL_NINJA_LAND_TEXTURES);
USE_ASSET(LEVEL_ROOKIE_MOUNTAIN_TEXTURES);

USE_ASSET(LEVEL_BIG_SNOWMAN_SPRITES);
USE_ASSET(LEVEL_SUNSET_ROCK_SPRITES);
USE_ASSET(LEVEL_NIGHT_HIGHWAY_SPRITES);
USE_ASSET(LEVEL_GRASS_VALLEY_SPRITES);
USE_ASSET(LEVEL_DIZZY_LAND_SPRITES);
USE_ASSET(LEVEL_QUICKSAND_VALLEY_SPRITES);
USE_ASSET(LEVEL_SILVER_MOUNTAIN_SPRITES);
USE_ASSET(LEVEL_NINJA_LAND_SPRITES);
USE_ASSET(LEVEL_ROOKIE_MOUNTAIN_SPRITES);

USE_ASSET(LEVEL_BIG_SNOWMAN_SURFACE_DATA);
USE_ASSET(LEVEL_SUNSET_ROCK_SURFACE_DATA);
USE_ASSET(LEVEL_NIGHT_HIGHWAY_SURFACE_DATA);
USE_ASSET(LEVEL_GRASS_VALLEY_SURFACE_DATA);
USE_ASSET(LEVEL_DIZZY_LAND_SURFACE_DATA);
USE_ASSET(LEVEL_QUICKSAND_VALLEY_SURFACE_DATA);
USE_ASSET(LEVEL_SILVER_MOUNTAIN_SURFACE_DATA);
USE_ASSET(LEVEL_ANIMAL_LAND_SURFACE_DATA);
USE_ASSET(LEVEL_NINJA_LAND_SURFACE_DATA);
USE_ASSET(LEVEL_ROOKIE_MOUNTAIN_SURFACE_DATA);

#endif
