#ifndef ASSETS_H
#define ASSETS_H

#include "game/engine/system_runtime.h"

#define LOAD_ASSET(id, handleIndex) \
    loadCompressedRomAsset((void *)&id##_ROM_START, (void *)&id##_ROM_END, handleIndex)
#define ASSET_SIZE(id) ((u8 *)&id##_ROM_END - (u8 *)&id##_ROM_START)

USE_ASSET(LEVEL_BIG_SNOWMAN);
USE_ASSET(LEVEL_SUNSET_ROCK);
USE_ASSET(LEVEL_NIGHT_HIGHWAY);
USE_ASSET(LEVEL_GRASS_VALLEY);
USE_ASSET(LEVEL_DIZZY_LAND);
USE_ASSET(LEVEL_QUICKSAND_VALLEY);
USE_ASSET(LEVEL_SILVER_MOUNTAIN);
USE_ASSET(LEVEL_ANIMAL_LAND);
USE_ASSET(LEVEL_NINJA_LAND);
USE_ASSET(LEVEL_ROOKIE_MOUNTAIN);

USE_ASSET(LEVEL_BIG_SNOWMAN_TEXTURES);
USE_ASSET(LEVEL_SUNSET_ROCK_TEXTURES);
USE_ASSET(LEVEL_NIGHT_HIGHWAY_TEXTURES);
USE_ASSET(LEVEL_GRASS_VALLEY_TEXTURES);
USE_ASSET(LEVEL_DIZZY_LAND_TEXTURES);
USE_ASSET(LEVEL_QUICKSAND_VALLEY_TEXTURES);
USE_ASSET(LEVEL_SILVER_MOUNTAIN_TEXTURES);
USE_ASSET(LEVEL_ANIMAL_LAND_TEXTURES);
USE_ASSET(LEVEL_NINJA_LAND_TEXTURES);
USE_ASSET(LEVEL_ROOKIE_MOUNTAIN_TEXTURES);

USE_ASSET(LEVEL_BIG_SNOWMAN_SPRITES);
USE_ASSET(LEVEL_SUNSET_ROCK_SPRITES);
USE_ASSET(LEVEL_NIGHT_HIGHWAY_SPRITES);
USE_ASSET(LEVEL_GRASS_VALLEY_SPRITES);
USE_ASSET(LEVEL_DIZZY_LAND_SPRITES);
USE_ASSET(LEVEL_QUICKSAND_VALLEY_SPRITES);
USE_ASSET(LEVEL_SILVER_MOUNTAIN_SPRITES);
USE_ASSET(LEVEL_NINJA_LAND_SPRITES);
USE_ASSET(LEVEL_ROOKIE_MOUNTAIN_SPRITES);

USE_ASSET(LEVEL_BIG_SNOWMAN_SURFACE_DATA);
USE_ASSET(LEVEL_SUNSET_ROCK_SURFACE_DATA);
USE_ASSET(LEVEL_NIGHT_HIGHWAY_SURFACE_DATA);
USE_ASSET(LEVEL_GRASS_VALLEY_SURFACE_DATA);
USE_ASSET(LEVEL_DIZZY_LAND_SURFACE_DATA);
USE_ASSET(LEVEL_QUICKSAND_VALLEY_SURFACE_DATA);
USE_ASSET(LEVEL_SILVER_MOUNTAIN_SURFACE_DATA);
USE_ASSET(LEVEL_ANIMAL_LAND_SURFACE_DATA);
USE_ASSET(LEVEL_NINJA_LAND_SURFACE_DATA);
USE_ASSET(LEVEL_ROOKIE_MOUNTAIN_SURFACE_DATA);

USE_ASSET(_1D82B0);
USE_ASSET(_1DCED0);
USE_ASSET(_1DE360);
USE_ASSET(_1E0F70);
USE_ASSET(_1E74E0);
USE_ASSET(_1EF530);
USE_ASSET(_1F1A90);
USE_ASSET(_215BE0);
USE_ASSET(_2427D0);
USE_ASSET(_243270);
USE_ASSET(_245A80);
USE_ASSET(_24C8E0);
USE_ASSET(_275A90);
USE_ASSET(_593D10);
USE_ASSET(_598A70);
USE_ASSET(_59AAA0);
USE_ASSET(_59DFE0);
USE_ASSET(_5A1ED0);
USE_ASSET(_5CBA80);
USE_ASSET(_5CCD40);
USE_ASSET(_5D4280);
USE_ASSET(_5DAF30);
USE_ASSET(_5DB9D0);
USE_ASSET(_5DCBE0);
USE_ASSET(_5DFDD0);
USE_ASSET(_5E0350);
USE_ASSET(_5E0E40);
USE_ASSET(_5E26E0);
USE_ASSET(_5E34A0);
USE_ASSET(_608560);
USE_ASSET(_609AA0);
USE_ASSET(_60ECB0);
USE_ASSET(_60F1A0);

#endif
