#ifndef ASSETS_H
#define ASSETS_H

#include "game/engine/system_runtime.h"

#define ASSET_SIZE(id) ((u8 *)&id##_ROM_END - (u8 *)&id##_ROM_START)

USE_ASSET(LEVEL_BIG_SNOWMAN);
USE_ASSET(LEVEL_SUNSET_ROCK);
USE_ASSET(LEVEL_NIGHT_HIGHWAY);
USE_ASSET(LEVEL_GRASS_VALLEY);
USE_ASSET(LEVEL_DIZZY_LAND);
USE_ASSET(LEVEL_QUICKSAND_VALLEY);
USE_ASSET(LEVEL_SILVER_MOUNTAIN);
USE_ASSET(LEVEL_ANIMAL_LAND);
USE_ASSET(LEVEL_NINJA_LAND);
USE_ASSET(LEVEL_ROOKIE_MOUNTAIN);

#endif
