#ifndef CONTROLLER_PAK_RACE_RECORD_SAVE_UI_H
#define CONTROLLER_PAK_RACE_RECORD_SAVE_UI_H

#include "common.h"

typedef struct ControllerPakRaceRecordSaveActor ControllerPakRaceRecordSaveActor;

void drawControllerPakRaceRecordSaveScorePanel(ControllerPakRaceRecordSaveActor *arg0);
void updateControllerPakRaceRecordSaveScorePanel(ControllerPakRaceRecordSaveActor *arg0);
void initControllerPakRaceRecordSaveScorePanel(ControllerPakRaceRecordSaveActor *arg0);
void drawControllerPakRaceRecordSavePromptFrame(ControllerPakRaceRecordSaveActor *arg0);
void updateControllerPakRaceRecordSavePromptFrame(ControllerPakRaceRecordSaveActor *arg0);
void initControllerPakRaceRecordSavePromptFrame(ControllerPakRaceRecordSaveActor *arg0);
void drawControllerPakRaceRecordSaveStatusMessage(ControllerPakRaceRecordSaveActor *arg0);
void updateControllerPakRaceRecordSaveStatusMessage(ControllerPakRaceRecordSaveActor *arg0);
void initControllerPakRaceRecordSaveStatusMessage(ControllerPakRaceRecordSaveActor *arg0);
void drawControllerPakRaceRecordSaveStatusChoicePrompt(ControllerPakRaceRecordSaveActor *arg0);
void updateControllerPakRaceRecordSaveStatusChoicePrompt(ControllerPakRaceRecordSaveActor *arg0);
void initControllerPakRaceRecordSaveStatusChoicePrompt(ControllerPakRaceRecordSaveActor *arg0);
void drawControllerPakRaceRecordSaveExitMessage(ControllerPakRaceRecordSaveActor *arg0);
void updateControllerPakRaceRecordSaveExitMessage(ControllerPakRaceRecordSaveActor *arg0);
void initControllerPakRaceRecordSaveExitMessage(ControllerPakRaceRecordSaveActor *arg0);

#endif
