#ifndef CONTROLLER_PAK_POST_RACE_SAVE_WARNING_FLOW_H
#define CONTROLLER_PAK_POST_RACE_SAVE_WARNING_FLOW_H

void initControllerPakPostRaceSaveWarningFlow(void);
void fadeInControllerPakPostRaceSaveWarningFirstMessage(void);
void fadeOutControllerPakPostRaceSaveWarningFirstMessage(void);
void waitBeforeControllerPakPostRaceSaveWarningSecondMessage(void);
void fadeInControllerPakPostRaceSaveWarningSecondMessage(void);
void fadeOutControllerPakPostRaceSaveWarningFlow(void);

#endif
