#ifndef CONTROLLER_PAK_REPLAY_SAVE_PROMPT_FLOW_H
#define CONTROLLER_PAK_REPLAY_SAVE_PROMPT_FLOW_H

void initControllerPakReplaySavePromptFlow(void);
void fadeInControllerPakReplaySavePromptFirstPage(void);
void fadeOutControllerPakReplaySavePromptFirstPage(void);
void waitBeforeControllerPakReplaySavePromptSecondPage(void);
void fadeInControllerPakReplaySavePromptSecondPage(void);
void fadeOutControllerPakReplaySavePromptFlow(void);

#endif
