#ifndef CONTROLLER_PAK_REPLAY_SAVE_PROMPT_FLOW_H
#define CONTROLLER_PAK_REPLAY_SAVE_PROMPT_FLOW_H

void initControllerPakReplaySavePromptFlow(void);
void updateControllerPakReplaySavePromptFirstPageFadeIn(void);
void updateControllerPakReplaySavePromptFirstPageFadeOut(void);
void waitForControllerPakReplaySavePromptSecondPage(void);
void updateControllerPakReplaySavePromptSecondPageFadeIn(void);
void fadeOutControllerPakReplaySavePromptFlow(void);

#endif
