#ifndef CONTROLLER_PAK_REPLAY_SAVE_NOTICE_FLOW_H
#define CONTROLLER_PAK_REPLAY_SAVE_NOTICE_FLOW_H

void initControllerPakReplaySaveNoticeFlow(void);
void fadeInControllerPakReplaySaveNoticeFirstPage(void);
void fadeOutControllerPakReplaySaveNoticeFirstPage(void);
void waitBeforeControllerPakReplaySaveNoticeSecondPage(void);
void fadeInControllerPakReplaySaveNoticeSecondPage(void);
void fadeOutControllerPakReplaySaveNoticeFlow(void);

#endif
