#ifndef ENDING_SEQUENCE_CAPTIONS_H
#define ENDING_SEQUENCE_CAPTIONS_H

#include "common.h"

typedef struct EndingSequenceCaptionActor EndingSequenceCaptionActor;
typedef struct EndingSequenceSpriteDebugViewerActor EndingSequenceSpriteDebugViewerActor;

void initEndingSequenceCaptionActor(EndingSequenceCaptionActor *arg0);
void initEndingSequenceSpriteDebugViewerActor(EndingSequenceSpriteDebugViewerActor *arg0);

#endif
