#ifndef ENDING_SEQUENCE_CREDITS_UI_H
#define ENDING_SEQUENCE_CREDITS_UI_H

#include "common.h"

typedef struct EndingSequenceCreditRollActor EndingSequenceCreditRollActor;
typedef struct EndingSequenceObjectSpriteDebugViewerActor EndingSequenceObjectSpriteDebugViewerActor;

void initEndingSequenceCreditRollActor(EndingSequenceCreditRollActor *arg0);
void initEndingSequenceObjectSpriteDebugViewerActor(EndingSequenceObjectSpriteDebugViewerActor *arg0);

#endif
