#ifndef ENDING_SEQUENCE_UI_H
#define ENDING_SEQUENCE_UI_H

#include "common.h"

typedef struct EndingSequenceCreditsAndTheEndActor EndingSequenceCreditsAndTheEndActor;
typedef struct EndingSequenceObjectSpriteDebugViewerActor EndingSequenceObjectSpriteDebugViewerActor;

void initEndingSequenceCreditsAndTheEndActor(EndingSequenceCreditsAndTheEndActor *arg0);
void initEndingSequenceObjectSpriteDebugViewerActor(EndingSequenceObjectSpriteDebugViewerActor *arg0);

#endif
