#ifndef RACE_PLAYER_UPDATE_H
#define RACE_PLAYER_UPDATE_H

#include "common.h"
struct RaceInputPlayer;

void initRacePlayers(void);
void applyRacePlayerTuning(struct RaceInputPlayer *player);
void initRacePlayer(struct RaceInputPlayer *player);
void updateRacePlayers(void);
void updateRacePlayer(struct RaceInputPlayer *player);
void updateRacePlayerMotionFeedback(struct RaceInputPlayer *player);
void updateRacePlayerMode00Grounded(struct RaceInputPlayer *player);
void updateRacePlayerMode29Crash(struct RaceInputPlayer *player);
void updateRacePlayerMode01JumpStart(struct RaceInputPlayer *player);
void updateRacePlayerMode22Airborne(struct RaceInputPlayer *player);
void dispatchRacePlayerAirborneMode(struct RaceInputPlayer *player);
void updateRacePlayerAirborneLaunch(struct RaceInputPlayer *player);
void updateRacePlayerAirborneCruise(struct RaceInputPlayer *player);
void resetRacePlayerTrickSubstate(struct RaceInputPlayer *player);
void updateRacePlayerTrickSubstate(struct RaceInputPlayer *player);
void updateRacePlayerTrickSubstateStart(struct RaceInputPlayer *player);
void updateRacePlayerTrickSubstateHold(struct RaceInputPlayer *player);
void updateRacePlayerTrickSubstateFinish(struct RaceInputPlayer *player);
void updateRacePlayerTrickSubstateNoop(s32 arg0);
void updateRacePlayerMode13AerialTrick(struct RaceInputPlayer *player);
void updateRacePlayerMode15AerialTrick(struct RaceInputPlayer *player);
void updateRacePlayerMode16AerialTrick(struct RaceInputPlayer *player);
void updateRacePlayerMode17AerialTrick(struct RaceInputPlayer *player);
void updateRacePlayerMode18AerialTrick(struct RaceInputPlayer *player);
void updateRacePlayerMode19AerialTrick(struct RaceInputPlayer *player);
void updateRacePlayerMode20AerialTrick(struct RaceInputPlayer *player);
void updateRacePlayerMode21AerialTrick(struct RaceInputPlayer *player);
void updateRacePlayerMode31AerialTrick(struct RaceInputPlayer *player);
void updateRacePlayerMode41AerialTrick(struct RaceInputPlayer *player);
void updateRacePlayerMode42AerialTrick(struct RaceInputPlayer *player);
void updateRacePlayerMode43AerialTrick(struct RaceInputPlayer *player);
void updateRacePlayerMode32AerialTrick(struct RaceInputPlayer *player);
void updateRacePlayerMode33AerialTrick(struct RaceInputPlayer *player);
void updateRacePlayerMode34AerialTrick(struct RaceInputPlayer *player);
void updateRacePlayerMode44AerialTrick(struct RaceInputPlayer *player);
void updateRacePlayerMode45AerialTrick(struct RaceInputPlayer *player);
void updateRacePlayerMode46AerialTrick(struct RaceInputPlayer *player);
void updateRacePlayerMode35AerialTrick(struct RaceInputPlayer *player);
void updateRacePlayerMode36AerialTrick(struct RaceInputPlayer *player);
void updateRacePlayerMode47AerialTrick(struct RaceInputPlayer *player);
void updateRacePlayerMode48AerialTrick(struct RaceInputPlayer *player);
void updateRacePlayerMode49AerialTrick(struct RaceInputPlayer *player);
void updateRacePlayerMode37AerialTrick(struct RaceInputPlayer *player);
void updateRacePlayerMode50AerialTrick(struct RaceInputPlayer *player);
void updateRacePlayerMode51AerialTrick(struct RaceInputPlayer *player);
void updateRacePlayerMode52AerialTrick(struct RaceInputPlayer *player);
void updateRacePlayerMode38AerialTrick(struct RaceInputPlayer *player);
void updateRacePlayerMode53AerialTrick(struct RaceInputPlayer *player);
void updateRacePlayerMode54AerialTrick(struct RaceInputPlayer *player);
void updateRacePlayerMode39AerialTrick(struct RaceInputPlayer *player);
void updateRacePlayerMode55AerialTrick(struct RaceInputPlayer *player);
void updateRacePlayerMode56AerialTrick(struct RaceInputPlayer *player);
void updateRacePlayerMode57AerialTrick(struct RaceInputPlayer *player);
void updateRacePlayerMode03(struct RaceInputPlayer *player);
void updateRacePlayerMode04(struct RaceInputPlayer *player);
void updateRacePlayerMode05(struct RaceInputPlayer *player);
void updateRacePlayerMode08(struct RaceInputPlayer *player);
void updateRacePlayerMode06CourseObject(struct RaceInputPlayer *player);
void updateRacePlayerMode28CourseObject(struct RaceInputPlayer *player);
void updateRacePlayerMode09CourseObject(struct RaceInputPlayer *player);
void updateRacePlayerMode10CourseObject(struct RaceInputPlayer *player);
void updateRacePlayerMode12(struct RaceInputPlayer *player);
void updateRacePlayerMode11(struct RaceInputPlayer *player);
void updateRacePlayerMode26(struct RaceInputPlayer *player);
void updateRacePlayerMode14(struct RaceInputPlayer *player);
void updateRacePlayerMode23(struct RaceInputPlayer *player);
void updateRacePlayerMode24(struct RaceInputPlayer *player);
void updateRacePlayerMode25(struct RaceInputPlayer *player);
void updateRacePlayerMode27(struct RaceInputPlayer *player);
void updateRacePlayerMode40(struct RaceInputPlayer *player);
void dispatchRacePlayerMode07(struct RaceInputPlayer *player);
void updateRacePlayerMode07State0(struct RaceInputPlayer *player);
void updateRacePlayerMode07State1(struct RaceInputPlayer *player);
void updateRacePlayerMode07State2(struct RaceInputPlayer *player);
void updateRacePlayerMode07State3(struct RaceInputPlayer *player);
void updateRacePlayerMode07State4(struct RaceInputPlayer *player);
void updateRacePlayerMode07State5(struct RaceInputPlayer *player);
void updateRacePlayerMode07State6(struct RaceInputPlayer *player);
void updateRacePlayerMode07State7(struct RaceInputPlayer *player);
s32 isRacePlayerAttackingPlayer(s16 arg0);
void dispatchRacePlayerMode30(struct RaceInputPlayer *player);
void updateRacePlayerMode30State0(struct RaceInputPlayer *player);
void updateRacePlayerMode30State1(struct RaceInputPlayer *player);
void dispatchRacePlayerMode32Character(struct RaceInputPlayer *player);
void updateRacePlayerMode32Character0(struct RaceInputPlayer *player);
void updateRacePlayerMode32Character1(struct RaceInputPlayer *player);
void updateRacePlayerMode32Character2(struct RaceInputPlayer *player);
void updateRacePlayerMode32Character3(struct RaceInputPlayer *player);
void updateRacePlayerMode32Character4(struct RaceInputPlayer *player);
void updateRacePlayerMode32Character5(struct RaceInputPlayer *player);
void dispatchRacePlayerMode35Character(struct RaceInputPlayer *player);
void updateRacePlayerMode35Character0(struct RaceInputPlayer *player);
void updateRacePlayerMode35Character1(struct RaceInputPlayer *player);
void updateRacePlayerMode35Character2(struct RaceInputPlayer *player);
void updateRacePlayerMode35Character3(struct RaceInputPlayer *player);
void updateRacePlayerMode35Character4(struct RaceInputPlayer *player);
void updateRacePlayerMode35Character5(struct RaceInputPlayer *player);
void updateRacePlayersPostUpdate(void);
void updateRacePlayerPostUpdate(struct RaceInputPlayer *player);
void updateRacePlayerPostUpdateNoop(void);
void updateRacePlayerPostUpdateMode07(struct RaceInputPlayer *player);
void updateRacePlayerPostUpdateMode00(struct RaceInputPlayer *player);
void updateRacePlayerVoiceSounds(struct RaceInputPlayer *player);
void updateRacePlayerLoopingSound(struct RaceInputPlayer *player);
void updateRacePlayerPostUpdateMode22(struct RaceInputPlayer *player);
void updateRacePlayerPostUpdateAirborneTrick(struct RaceInputPlayer *player);
void updateRacePlayerPostUpdateMode02(struct RaceInputPlayer *player);
void updateRacePlayerPostUpdateMode03(struct RaceInputPlayer *player);
void updateRacePlayerPostUpdateMode29(struct RaceInputPlayer *player);
void updateRacePlayerPostUpdateMode30(struct RaceInputPlayer *player);

#endif
