#!/usr/bin/env python3
"""Validate the per-course inventory and generate shared C declarations."""

from __future__ import annotations

import argparse
import re
from pathlib import Path

import yaml


COURSE_COUNT = 10
COURSE_KINDS = {"standard", "trick", "secret"}
ASSET_KINDS = ("graphics", "model_resources", "surface_data", "sprites")
IDENTIFIER = re.compile(r"[A-Za-z_][A-Za-z0-9_]*\Z")


def parse_int(value: object) -> int:
    return int(value, 0) if isinstance(value, str) else int(value)


def load_courses(definitions_dir: Path) -> list[dict]:
    courses: list[dict] = []
    for path in sorted(definitions_dir.glob("*.yaml")):
        with path.open("r", encoding="utf-8") as stream:
            course = yaml.safe_load(stream)
        if not isinstance(course, dict):
            raise ValueError(f"{path}: course definition must be a mapping")
        course["_path"] = path
        courses.append(course)

    if len(courses) != COURSE_COUNT:
        raise ValueError(f"expected {COURSE_COUNT} courses, found {len(courses)}")

    ids = [parse_int(course.get("legacy_id", -1)) for course in courses]
    if sorted(ids) != list(range(COURSE_COUNT)):
        raise ValueError(f"legacy_id values must be contiguous from 0 to {COURSE_COUNT - 1}")

    keys: set[str] = set()
    enums: set[str] = set()
    for course in courses:
        path = course["_path"]
        for field in ("name", "key", "enum", "legacy_id", "kind", "uses", "assets", "render"):
            if field not in course:
                raise ValueError(f"{path}: missing {field}")
        key = str(course["key"])
        enum = str(course["enum"])
        if not re.fullmatch(r"[a-z][a-z0-9_]*", key):
            raise ValueError(f"{path}: key must be a lowercase identifier")
        if not re.fullmatch(r"[A-Z][A-Z0-9_]*", enum):
            raise ValueError(f"{path}: enum must be an uppercase identifier")
        if key in keys or enum in enums:
            raise ValueError(f"{path}: duplicate course identity")
        keys.add(key)
        enums.add(enum)
        if course["kind"] not in COURSE_KINDS:
            raise ValueError(f"{path}: unsupported kind {course['kind']!r}")
        if not isinstance(course["uses"], list) or not course["uses"]:
            raise ValueError(f"{path}: uses must be a non-empty list")

        assets = course["assets"]
        if set(assets) != set(ASSET_KINDS):
            raise ValueError(f"{path}: assets must define {', '.join(ASSET_KINDS)}")
        for asset_kind in ASSET_KINDS:
            asset = assets[asset_kind]
            if asset_kind == "sprites" and asset is None:
                continue
            if not isinstance(asset, dict) or set(asset) != {"symbol", "rom_start", "rom_end"}:
                raise ValueError(f"{path}: {asset_kind} requires symbol, rom_start, and rom_end")
            if not IDENTIFIER.fullmatch(str(asset["symbol"])):
                raise ValueError(f"{path}: invalid {asset_kind} symbol")
            if parse_int(asset["rom_start"]) >= parse_int(asset["rom_end"]):
                raise ValueError(f"{path}: invalid {asset_kind} ROM range")

        render = course["render"]
        required_render = {"main_display_list", "backdrop_display_lists", "scenery_entries", "scrolling_textures"}
        if set(render) != required_render:
            raise ValueError(f"{path}: render section has unexpected fields")
        if not isinstance(render["backdrop_display_lists"], list) or not isinstance(
            render["scrolling_textures"], list
        ):
            raise ValueError(f"{path}: render list fields must be lists")
        symbols = [
            render["main_display_list"],
            render["scenery_entries"],
            *render["backdrop_display_lists"],
            *render["scrolling_textures"],
        ]
        if any(not IDENTIFIER.fullmatch(str(symbol)) for symbol in symbols):
            raise ValueError(f"{path}: invalid render symbol")

    return sorted(courses, key=lambda course: parse_int(course["legacy_id"]))


def render_course_ids(courses: list[dict]) -> str:
    lines = ["/* Auto-generated by tools/generate_course_definitions.py. */"]
    lines.extend(f"    RACE_COURSE_{course['enum']} = {course['legacy_id']}," for course in courses)
    lines.append(f"    RACE_COURSE_COUNT = {COURSE_COUNT}")
    return "\n".join(lines) + "\n"


def render_asset_declarations(courses: list[dict]) -> str:
    lines = ["/* Auto-generated by tools/generate_course_definitions.py. */"]
    for course in courses:
        lines.append("")
        lines.append(f"/* {course['name']} */")
        for asset_kind in ASSET_KINDS:
            asset = course["assets"][asset_kind]
            if asset is not None:
                lines.append(f"USE_ASSET({asset['symbol']});")
    return "\n".join(lines) + "\n"


def generated_files(courses: list[dict]) -> dict[str, str]:
    return {
        "course_ids.inc": render_course_ids(courses),
        "course_asset_declarations.inc": render_asset_declarations(courses),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--definitions", type=Path, default=Path("config/courses"))
    parser.add_argument("--out-dir", type=Path, default=Path("include/generated"))
    parser.add_argument("--check", action="store_true", help="fail if checked-in generated files are stale")
    args = parser.parse_args()

    expected = generated_files(load_courses(args.definitions))
    stale = []
    for name, content in expected.items():
        path = args.out_dir / name
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != content:
                stale.append(str(path))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
    if stale:
        parser.error("stale generated files: " + ", ".join(stale))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
