.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

/* Handwritten function */
nonmatching entrypoint, 0x38

glabel entrypoint
    /* 1000 80000400 3C08800E */  lui        $t0, %hi(main_BSS_START)
    /* 1004 80000404 3C090007 */  lui        $t1, (0x7DAC0 >> 16)
    /* 1008 80000408 250829C0 */  addiu      $t0, $t0, %lo(main_BSS_START)
    /* 100C 8000040C 3529DAC0 */  ori        $t1, $t1, (0x7DAC0 & 0xFFFF)
  .L80000410:
    /* 1010 80000410 2129FFF8 */  addi       $t1, $t1, -0x8 /* handwritten instruction */
    /* 1014 80000414 AD000000 */  sw         $zero, 0x0($t0)
    /* 1018 80000418 AD000004 */  sw         $zero, 0x4($t0)
    /* 101C 8000041C 1520FFFC */  bnez       $t1, .L80000410
    /* 1020 80000420 21080008 */   addi      $t0, $t0, 0x8 /* handwritten instruction */
    /* 1024 80000424 3C0A800A */  lui        $t2, %hi(main)
    /* 1028 80000428 3C1D8032 */  lui        $sp, %hi(D_80322480)
    /* 102C 8000042C 254A96A0 */  addiu      $t2, $t2, %lo(main)
    /* 1030 80000430 01400008 */  jr         $t2
    /* 1034 80000434 27BD2480 */   addiu     $sp, $sp, %lo(D_80322480)
endlabel entrypoint
    /* 1038 80000438 00000000 */  nop
    /* 103C 8000043C 00000000 */  nop
    /* 1040 80000440 00000000 */  nop
    /* 1044 80000444 00000000 */  nop
    /* 1048 80000448 00000000 */  nop
    /* 104C 8000044C 00000000 */  nop
